name: Deploy Node App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t terr97us/nextjs-app --build-arg REACT_APP_CLOUD_NAME_CLOUDINARY= 'ddwo8iuhl'  .
      - name: Publish Image to docker hub
        run: docker push terr97us/nextjs-app:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from docker hub
        run: docker pull terr97us/nextjs-app:latest 
      - name: Delete old container
        run: docker rm -f nextjs-app-container  
      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name nextjs-app-container -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' terr97us/nextjs-app


  